all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "admin"
    ansible_password: "admin"

prod:
  hosts:
    client1:
      ansible_host: localhost
      db_qty: 1
      ansible_connection: local
      instance_1:
        name: Frazer
        port: 8080
        db_user: odoo
        db_pass: odoo

    client2:
      ansible_host: 10.0.2.4
      db_qty: 1
      instance_1:
        name: ENSUP
        port: 8080
        db_user: odoo
        db_pass: odoo
